Better formatting for README and contribution guidelines
sohsatoh/ReProvision-Reborn_old pull request #8
Opened 2021-03-22 03:04 UTC by TheRealKeto

This PR provides much cleaner documentation and contributing guidelines to the project, with better formatting and overall more cohesive writing. Suggestions of things to change/remove are welcome!

2021-03-22 11:24 UTC, sohsatoh requested changes
Thank you for your contribution!
Could you look at the change request and fix it? (Sorry, but I don't really wish to make a comparison between AltStore and ReProvision)

2021-03-22 11:24 UTC, sohsatoh commented on README.md
> +What separates AltStore and this project is the fact that ReProvision doesn't require a computer, making it a viable option for easy, on-device provisioning. Aside from that, this fork of ReProvision
Personally, I feel that it should be mentioned that ReProvision Reborn requires a jailbroken device (even if it is a re-declaration). Also, AltStore has AltDaemon. Personally, it would be better to delete this sentence and just use the second line.

2021-03-22 19:21 UTC, TheRealKeto commented on README.md
> +What separates AltStore and this project is the fact that ReProvision doesn't require a computer, making it a viable option for easy, on-device provisioning. Aside from that, this fork of ReProvision
This section accommodates for the fact that ReProvision Reborn isn't a competitor of AltStore, but if you want this section removed, I can remove it.

2021-03-23 05:25 UTC, sohsatoh approved these changes

2021-03-23 05:26 UTC, merged